### ISSUE TITLE
Drop Down menus

### ISSUE THREAD

**Issue by JamesGaier** [42flyingfish/fitting-room-webapp#1]
Only the hips measurement drop down menu changes the image.

**Comment by uhck** [comment]
I set it that way because there's set measurements for each size. Instead, do you want the size to be determined by at least 2 of the measurements or all 3 (hips, waist, chest) to match?

**Comment by JamesGaier** [comment]
Yea, I ended up having it be the average of the three.  Garry and I implemented a system that took the average of the three on Wednesday I think.

**Comment by JamesGaier** [comment]
We can change it later if we end up going with a openCV solution as that will most likely scale dynamically.
